apiVersion: v1
kind: Secret
metadata:
  name: k8s-whisperer-secrets
  namespace: default
type: Opaque
stringData:
  slack_bot_token: <SLACK_BOT_TOKEN>
  slack_signing_secret: <SLACK_SIGNING_SECRET>
  gemini_api_key: <GEMINI_API_KEY>
